services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:2.35.7
    container_name: n8n
    restart: unless-stopped

    ports:
      - "5678:5678"

    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${POSTGRES_HOST}
      DB_POSTGRESDB_PORT: ${POSTGRES_PORT}
      DB_POSTGRESDB_DATABASE: ${N8N_DB_NAME}
      DB_POSTGRESDB_USER: ${N8N_DB_USER}
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_PASSWORD}

      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}

      TZ: ${TZ}
      GENERIC_TIMEZONE: ${TZ}

    volumes:
      - ${APPDATA}/n8n:/home/node/.n8n
    networks:
      - automation
