services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:1
    container_name: cloudflare-ddns
    network_mode: host
    restart: unless-stopped
    user: "1000:1000"
    read_only: true
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
      - DOMAINS=jellyfin.lgrayland.com,sonarr.lgrayland.com,mealie.lgrayland.com,radarr.lgrayland.com,homeconsole.lgrayland.com
      - PROXIED=false
