services:
  ddns-route53:
    image: crazymax/ddns-route53:latest
    container_name: ddns-route53
    environment:
      TZ: $TZ
      SCHEDULE: "*/30 * * * *"
      LOG_LEVEL: "info"
      LOG_JSON: "false"
      DDNSR53_CREDENTIALS_ACCESSKEYID: $AWS_ACCESS_KEY_ID
      DDNSR53_CREDENTIALS_SECRETACCESSKEY: $AWS_SECRET_ACCESS_KEY
      DDNSR53_ROUTE53_HOSTEDZONEID: $ROUTE53_HOSTEDZONEID
      DDNSR53_ROUTE53_RECORDSSET_0_NAME: "vpn.lgrayland.com."
      DDNSR53_ROUTE53_RECORDSSET_0_TYPE: "A"
      DDNSR53_ROUTE53_RECORDSSET_0_TTL: "300"
      DDNSR53_ROUTE53_RECORDSSET_1_NAME: "jellyfin.lgrayland.com."
      DDNSR53_ROUTE53_RECORDSSET_1_TYPE: "A"
      DDNSR53_ROUTE53_RECORDSSET_1_TTL: "300"
      DDNSR53_ROUTE53_RECORDSSET_2_NAME: "sonarr.lgrayland.com."
      DDNSR53_ROUTE53_RECORDSSET_2_TYPE: "A"
      DDNSR53_ROUTE53_RECORDSSET_2_TTL: "300"
      DDNSR53_ROUTE53_RECORDSSET_3_NAME: "mealie.lgrayland.com."
      DDNSR53_ROUTE53_RECORDSSET_3_TYPE: "A"
      DDNSR53_ROUTE53_RECORDSSET_3_TTL: "300"
      DDNSR53_ROUTE53_RECORDSSET_4_NAME: "radarr.lgrayland.com."
      DDNSR53_ROUTE53_RECORDSSET_4_TYPE: "A"
      DDNSR53_ROUTE53_RECORDSSET_4_TTL: "300"
      DDNSR53_ROUTE53_RECORDSSET_5_NAME: "homeconsole.lgrayland.com."
      DDNSR53_ROUTE53_RECORDSSET_5_TYPE: "A"
      DDNSR53_ROUTE53_RECORDSSET_5_TTL: "300"
      DDNSR53_ROUTE53_RECORDSSET_6_NAME: "reitti.lgrayland.com."
      DDNSR53_ROUTE53_RECORDSSET_6_TYPE: "A"
      DDNSR53_ROUTE53_RECORDSSET_6_TTL: "300"
    restart: always
