services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - 5432:5432
    volumes:
      - $APPDATA/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
